Repository ROAR-QUTRC/perseus-v2, pull requests merged in 2025-01, with the labels that each got.

#65 feat: Package `groot2`
  flake.nix
  packages/groot2/default.nix
  packages/overlay.nix
Labels: 05-enhancement, 20-software

#69 Autonomy: CMakeLists.txt and launch file aligned with Project
  software/ros_ws/nix-packages/autonomy.nix
  software/ros_ws/nix-packages/input-devices.nix
  software/ros_ws/nix-packages/overlay.nix
  software/ros_ws/src/autonomy/CMakeLists.txt
  software/ros_ws/src/autonomy/README.md
  software/ros_ws/src/autonomy/launch/mapping_using_slam_toolbox.launch.py
  software/ros_ws/src/autonomy/package.xml
Labels: 21-ros

#84 documentation: Added a warning to stage ROS2 packages pre nix build
  docs/source/architecture/software.md
Labels: 02-documentation

#97 Update README.md
  software/README.md
Labels: 02-documentation
