Repository ROAR-QUTRC/perseus-v2, pull requests merged in 2025-03, with the labels that each got.

#143 ci/fix docs deployment
  .github/workflows/all.yaml
Labels: 26-ci/cd

#150 docs: Clarify minor points
  docs/source/standards/software.md
Labels: 02-documentation

#156 feat: Add realsense2-camera dependency
  software/ros_ws/nix-packages/perseus-sensors.nix
  software/ros_ws/patches.nix
  software/ros_ws/src/perseus_sensors/package.xml
Labels: 21-ros

#172 feat: Use CycloneDDS RMW
  flake.nix
Labels: 01-bug, 21-ros
