Repository ROAR-QUTRC/perseus-v2, pull requests merged in 2025-02, with the labels that each got.

#101 ci: Remove deprecated Magic Nix Cache
  .github/workflows/all.yaml
  .github/workflows/intersphinx.yaml
Labels: 01-bug, 26-ci/cd

#102 Added the m2m2 lidar to the Perseus description
  software/ros_ws/src/perseus_description/urdf/sensors.urdf.xacro
Labels: 21-ros

#106 Fixed RGB ordering
  firmware/light-tower/src/main.cpp
Labels: 05-enhancement

#108 docs: Instructions for teleoperation added
  firmware/light-tower/.vscode/extensions.json
Labels: 02-documentation

#110 Bugfix - perseus_sensors (m2m2_lidar): bug fix that the version appended
  software/ros_ws/src/perseus_sensors/CMakeLists.txt
Labels: 01-bug, 20-software

#112 perseus_simulation: changed the controller launch sequence
  software/ros_ws/src/perseus/launch/controllers.launch.py
  software/ros_ws/src/perseus_description/urdf/sensors.urdf.xacro
Labels: 01-bug

#123 Bugfix/m2m2 lidar
  software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
Labels: 01-bug, 70-hardware, 20-software

#122 docs: Updated teleop page with current network details.
  docs/source/home/teleoperation.md
Labels: 02-documentation

#132 Fix: Nix setup script updated for new Determinate Nix installer
  software/scripts/nix-setup.sh
Labels: 01-bug, 61-nix, 20-software

#136 Bugfix/bash on orin
  software/home-manager/cli-programs/term-multiplexing.nix
Labels: 01-bug

#137 perseus_sensors(m2m2_lidar): Added param for reading the imu or not
  software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
  software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
Labels: 01-bug
