Repository ROAR-QUTRC/perseus-v2, pull requests merged in 2025-08, with the labels that each got.

#230 docs: Update the perseus simulation tutorial
  docs/source/tutorials/running-simulation.md
Labels: 02-documentation

#238 Docs/autonomy 2026 team nigel
  docs/source/challenge-breakdowns/autonomy-and-mapping.md
Labels: 02-documentation

#250 Fix GitHub Actions config and CODEOWNERS
  .github/CODEOWNERS
  .github/workflows/all.yaml
  .github/workflows/firmware.yaml
Labels: 26-ci/cd

#240 docs(autonomy and mapping): Added Lachlan Ikeguchi to the 2026 team members.
  docs/source/challenge-breakdowns/autonomy-and-mapping.md
Labels: 02-documentation

#181 Feat/arm teleop direct script
  flake.nix
  perseus-v2.code-workspace
  software/arm-teleop-direct/CMakeLists.txt
  software/arm-teleop-direct/README.md
  software/arm-teleop-direct/include/perseus-arm-teleop.hpp
  software/arm-teleop-direct/include/servo-constants.hpp
  software/arm-teleop-direct/src/main.cpp
  software/arm-teleop-direct/src/perseus-arm-teleop.cpp
  software/ros_ws/nix-packages/perseus-can-if.nix
  software/shared/simple-networking/include/simple_networking/core.hpp
Labels: 25-native, 20-software, 80-2026
